DOCKERCOMPOSE := docker compose

DOCKERCOMPOSE_API := api
DOCKERCOMPOSE_MIGRATE_UP := migrate-up
DOCKERCOMPOSE_MIGRATE_DOWN := migrate-down
DOCKERCOMPOSE_BLOCKCHAIN := blockchain
DOCKERCOMPOSE_CRAWLER := crawler
DOCKERCOMPOSE_CRONJOB := cronjob
DOCKERCOMPOSE_POSTGRES := postgres
DOCKERCOMPOSE_REDIS := redis

RUN_API := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_API)
RUN_MIGRATE_UP := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_MIGRATE_UP)
RUN_MIGRATE_DOWN := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_MIGRATE_DOWN)
RUN_BLOCKCHAIN := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_BLOCKCHAIN)
RUN_CRAWLER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_CRAWLER)
RUN_CRONJOB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_CRONJOB)
RUN_POSTGRES := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_POSTGRES)
RUN_REDIS := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_REDIS)

RUN := $(DOCKERCOMPOSE) up -d

STOP_API := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_API) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_API)
STOP_MIGRATE := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_MIGRATE) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_MIGRATE)
STOP_BLOCKCHAIN := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_BLOCKCHAIN) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_BLOCKCHAIN)
STOP_CRAWLER := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_CRAWLER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_CRAWLER)
STOP_CRONJOB := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_CRONJOB) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_CRONJOB)
STOP_POSTGRES := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_POSTGRES) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_POSTGRES)
STOP_REDIS := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_REDIS) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_REDIS)

.PHONY: run
run: ## Runs a full node
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_CRONJOB)
	$(RUN_CRAWLER)
	$(RUN_BLOCKCHAIN)
	$(RUN_API)

.PHONY: run-build
run-build: ## Runs a full node
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_CRONJOB) --build
	$(RUN_CRAWLER) --build
	$(RUN_BLOCKCHAIN) --build
	$(RUN_API) --build


.PHONY: stop
stop: ## Runs a full node
	$(STOP_API)
	$(STOP_BLOCKCHAIN)
	$(STOP_CRAWLER)
	$(STOP_CRONJOB)
	$(STOP_POSTGRES)
	$(STOP_REDIS)


.PHONY: run-migrate-up
run-migrate-up: ## Runs a full node
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_MIGRATE_UP)

.PHONY: run-migrate-down
run-migrate-down: ## Runs a full node
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_MIGRATE_DOWN)

.PHONY: run-db
run-db: ## Runs a full node
	$(RUN_POSTGRES)
	$(RUN_REDIS)
