name: Build React Native App

env:
  FIREBASE_CONNECT: '{

}'


on:
  push:
    branches:
      - develop_mobile
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Fastlane
        run: bundle install

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      
      #- name: Setup firebase connect
      #  run: echo ${{env.FIREBASE_CONNECT}} > android/fastlane/firebase-connect.json && echo ${{env.FIREBASE_CONNECT}} > android/fastlane/firebase-connect.json

      - name: Build Android
        run: cd android && fastlane beta && cd ..

      - name: Build iOS
        run: cd ios && pod install && fastlane beta && cd ..
